
stages:          # List of stages for jobs, and their order of execution
  - build
  - release

build-job:       # This job runs in the build stage, which runs first.
  image: node:14-buster-slim
  stage: build
  rules:
    - if: $CI_COMMIT_TAG                 # Run this job when a tag is created
      when: never
  script:
    - npm i --production
    - npm run build

release_job:
  image: node:14-buster-slim
  stage: build
  rules:
    - if: $CI_COMMIT_TAG                 # Run this job when a tag is created
  script:
    - npm i --production
    - npm run build
    - ls -la .next/
    - ls -la .next/standalone/
    - mkdir -p ./output
    - cp -r .next/standalone/* ./output/
    - mkdir -p "./output/.next/"
    - ls -la ./output/
    - cp -r ".next/standalone/.next" "./output/"
    - ls -la ./output/
    - ls -la ./output/.next
    - cp -r ".next/static" "./output/.next"
    - ls -la ./output/.next
    - cp -r public ./output/
    - ls -la ./output/
    - cp newrelic.js ./output/
  artifacts:
    name: petclinic-react-next-front
    paths:
      - ./output/
    expire_in: 1 weeks 
